### ISSUE TITLE
XAdES-B-LTA

### ISSUE THREAD

**Issue by djnice** [agyonov/CryptoEx#4]
Dear Aleksandar,
Please add XAdES-B-LTA profile handling.
Thanks!

**Comment by agyonov** [comment]
Hi djnice,

As you correctly have seen with version 1.x you can create Baseline-B and Baseline-T signatures.
I have just uploaded version 2.x with wich you can create also Baseline-LT signatures.

I am currently working on the last level - the Baseline-LTA and I will do my best to publish this feature in the upcoming weeks.

regards

**Comment by agyonov** [comment]
Hi djnice,

 Baseline-LTA is ready. v. 2.0.1. Also updated the Wiki to have description for T, LT and LTA

For XAdES-LTA - look test method 'TestETSIXml.Test_XML_RSA_Enveloped_Timestamped_LTA'
For JAdES-LTA - similar test method 'TestETSI.Test_ETSI_RSA_Timestamp_LTA_Enveloped'

regards

**Comment by djnice** [comment]
Many thanks!
